package com.yogesh.feign;

import com.yogesh.entity.QuestionWrapper;
import com.yogesh.entity.Response;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

//which micro service we are going to communicate
@FeignClient("QUESTION-SERVICE")
public interface QuizInterface {
    // paste the methods present in QUESTION-SERVICE

    //generate //give only question id's // then these group of id's are mapped with single quiz id.
    @GetMapping("question/generate")
    public ResponseEntity<List<Integer>> getQuestionsForQuiz
    (@RequestParam String categoryName, @RequestParam Integer noOfQuestions);

    //getQuestions based on the given question Id's // the id's are previously generated by previous method
    //QuestionWrapper returned bcoz no need to send the answers with question for quiz
    @PostMapping("question/getQuestions")
    public ResponseEntity<List<QuestionWrapper>> getQuestionsFromId(@RequestBody List<Integer> questionIds);

    //getScore
    //using quiz result we can calculate the score of the result
    @PostMapping("question/getScore")
    public ResponseEntity<Integer> getScore(@RequestBody List<Response> responses);
}
